model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/sdr" # name of the logged metric which determines when model is improving
  save_top_k: 5 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  mode: "max" # can be "max" or "min"
  verbose: False
  dirpath: "checkpoints/"
  filename: "{epoch:02d}"
#
early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/sdr" # name of the logged metric which determines when model is improving
  patience: 300 # how many epochs of not improving until training stops
  mode: "max" # can be "max" or "min"
  min_delta: 0.05 # minimum change in the monitored metric needed to qualify as an improvement

make_onnx:
  _target_: src.callbacks.onnx_callback.MakeONNXCallback
  dirpath: "onnx/"

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: "epoch"